version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./DotNetCore.sln && dotnet publish ./DotNetCore.sln -c Release -o ./obj/Docker/publish"
